# Generated by Django 4.2.7 on 2023-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=64, verbose_name='Название новости')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('intro', models.CharField(max_length=250, verbose_name='Краткое описание статьи')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, upload_to='photos/uploaded/%Y/%m/%d/', verbose_name='Фотография')),
                ('is_modarated', models.BooleanField(default=True, verbose_name='Проведена ли была модерация?')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
