# Generated by Django 4.2.7 on 2023-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=64, verbose_name='Название новости')),
                ('intro', models.CharField(max_length=250, verbose_name='Краткое описание статьи')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
