# Generated by Django 4.2.7 on 2023-12-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(max_length=1024, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_modarated',
            field=models.BooleanField(verbose_name='Проведена ли была модерация?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
